version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.10.2
    ports:
      - "80:80"
    volumes:
      - moodle-mount-sync:/usr/share/nginx/html/moodle:nocopy
      - ./default.conf:/etc/nginx/conf.d/default.conf.backup
    environment:
      - XDEBUG_REMOTE_ADDR=$XDEBUG_REMOTE_ADDR
    command: /bin/bash -c "envsubst '$$XDEBUG_REMOTE_ADDR' < /etc/nginx/conf.d/default.conf.backup > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' && mkdir /var/moodledata && chmod 777 /var/moodledata"

  postgres:
    container_name: postgres
    image: postgres:9.5.6
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  phpfpm:
    container_name: phpfpm
    image: mfabriczy/docker-moodle-phpfpm:1.0
    volumes:
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - moodle-mount-sync:/usr/share/nginx/html/moodle:nocopy
      - behat-dump-sync:/var/moodle_behat_output:nocopy
  selenium:
    container_name: selenium
    image: selenium/standalone-firefox:2.53.1-beryllium
    volumes:
      - ${LOCAL_MOODLE_PATH}:/var/www/html/moodle:ro

volumes:
  moodle-mount-sync:
    external: true
  behat-dump-sync:
    external: true
