version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.10.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - moodle-mount-sync:/usr/share/nginx/html/moodle:nocopy
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./tls/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./tls/nginx.key:/etc/nginx/ssl/nginx.key
  postgres:
    container_name: postgres
    image: postgres:9.5.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  phpfpm:
    container_name: phpfpm
    image: mfabriczy/docker-moodle-phpfpm:1.1
    volumes:
      - moodle-mount-sync:/usr/share/nginx/html/moodle:nocopy
      - behat-dump-sync:/var/moodle_behat_output:nocopy
  selenium:
    container_name: selenium
    image: selenium/standalone-firefox-debug:2.53.1
    ports:
      - "${VNC_PORT}:5900"
    volumes:
      - ${LOCAL_MOODLE_PATH}:/var/www/html/moodle:ro
  redis:
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:4.0.9-alpine

volumes:
  moodle-mount-sync:
    external: true
  behat-dump-sync:
    external: true
